### ISSUE TITLE
About NEU-DET source link

### ISSUE THREAD

**Issue by chairc** [halmusaibeli/metal-defect-datasets#1]
Hello, I found a little problem with your NEU-DET dataset link, the link of this dataset is [http://faculty.neu.edu.cn/songkechen/zh_CN/zdylm/263270/list](http://faculty.neu.edu.cn/songkechen/zh_CN/zdylm/263270/list)
And the google drive link is [https://drive.google.com/file/d/1qrdZlaDi272eA79b0uCwwqPrm2Q_WI3k/view](https://drive.google.com/file/d/1qrdZlaDi272eA79b0uCwwqPrm2Q_WI3k/view)
![image](https://user-images.githubusercontent.com/43342212/201363040-6e81aa0c-8c2c-4360-93c1-eebd51426ba9.png)

**Comment by robotbitdev** [comment]
Hi Yu Chen, 

Thanks for reaching out and providing the source link. I will update it right away.

Regards,
Hamdan
